version: "3.7"

services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge